dist: trusty
sudo: false
os: linux

language: haskell
cache:
  directories:
    - .cabal-sandbox

matrix:
  include:
  - ghc: "8.10"
    env: CACHE_NAME=CACHE8.10
    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
    script: cabal configure --enable-tests && cabal test --show-details=always

  - ghc: "8.8"
    env: CACHE_NAME=CACHE8.8
    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
    script: cabal configure --enable-tests && cabal test --show-details=always

  - ghc: "8.6"
    env: CACHE_NAME=CACHE8.6

  - ghc: "8.4"
    env: CACHE_NAME=CACHE8.4

  - ghc: "8.2"
    env: CACHE_NAME=CACHE8.2

  - ghc: "8.0"
    env: CACHE_NAME=CACHE8.0

  - ghc: "7.10"
    env: CACHE_NAME=CACHE7.10

  - ghc: "7.8"
    env: CACHE_NAME=CACHE7.8

  - ghc: "7.6"
    env: CACHE_NAME=CACHE7.6

  - ghc: "7.4"
    env: CACHE_NAME=CACHE7.4
    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
    script: cabal configure --enable-tests && cabal test --show-details=always

install : cabal sandbox init && cabal install --only-dependencies --enable-tests --enable-benchmarks --disable-documentation
script: cabal configure --enable-tests --enable-benchmarks && cabal test --show-details=always && cabal bench --benchmark-option="-obench.html"
